### ISSUE TITLE
There might be something wrong with the code. 

### ISSUE THREAD

**Issue by Vin1115** [LHRLAB/NQE#3]
https://github.com/LHRLAB/NQE/blob/63d63a40d70faf8c1cee9bba63f9ddca10c21f7b/src/new_model/HAHE.py#L105

According to your paper, the line of code cited above should be filled with "edge_value" instead of "edge_key", I wonder if this is intentional or by mistake. In addition, whether the experimental results reported in the paper were obtained by this "wrong" code.

**Comment by LHRLAB** [comment]
Thank you for your tip, after testing, the result is not affected.
